=== nexylmao/MiBP3/xsd_sema.xsd
<?xml.version = "1.0"?>
<xsd:schema 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="randomlink"
	xmlns="randomlink"
	>
	<xsd:element name="Uplatnice">
		<xsd:complexType>
			<xsd:sequence minOccurs = "1" maxOccurs = "unbounded">
				<xsd:element name="Uplatnica">
					<xsd:complexType>
						<xsd:sequence minOccurs="1" maxOccurs="1">
							<xsd:element name="Uplatilac" type="xsd:string"/>
							<xsd:element name="SvrhaPlacanja" type="xsd:string"/>
							<xsd:element name="Primalac" type="xsd:string"/>
							<xsd:element name="Iznos">
								<xsd:complexType>
									<xsd:sequence minOccurs="1" maxOccurs="1">
										<xsd:element name="Valuta">
											<xsd:simpleType>
												<xsd:restriction base="xsd:string">
													<xsd:minLength value="3"/>
													<xsd:maxLength value="3"/>
												</xsd:restriction>
											</xsd:simpleType>
										</xsd:element>
										<xsd:element name="Sifra">
											<xsd:simpleType>
												<xsd:restriction base="xsd:integer">
													<xsd:pattern value="\d{3}"/>
												</xsd:restriction>
											</xsd:simpleType>
										</xsd:element>
										<xsd:element name="Iznos">
											<xsd:simpleType>
												<xsd:restriction  base="xsd:decimal">
													<xsd:minInclusive value="0"/>
													<xsd:fractionDigits value="2"/>
													<xsd:pattern value="\d+\.\d{2}"/>
												</xsd:restriction>
											</xsd:simpleType>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="RacunUplatioca">
								<xsd:complexType>
									<xsd:sequence minOccurs="1" maxOccurs="1">
										<xsd:element name="Model">
											<xsd:simpleType>
												<xsd:restriction base="xsd:positiveInteger">
													<xsd:pattern value="\d{2}"/>
												</xsd:restriction>
											</xsd:simpleType>
										</xsd:element>
										<xsd:element name="BrojRacuna">
											<xsd:simpleType>
												<xsd:restriction base="xsd:string">
													<xsd:pattern value="\d{3}-\d{1,13}-\d{2}"/>
												</xsd:restriction>
											</xsd:simpleType>
										</xsd:element>
										<xsd:element name="PozivniBroj" type="xsd:string"/>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="RacunPrimaoca">
								<xsd:complexType>
									<xsd:sequence minOccurs="1" maxOccurs="1">
										<xsd:element name="Model">
											<xsd:simpleType>
												<xsd:restriction base="xsd:positiveInteger">
													<xsd:pattern value="\d{2}"/>
												</xsd:restriction>
											</xsd:simpleType>
										</xsd:element>
										<xsd:element name="BrojRacuna">
											<xsd:simpleType>
												<xsd:restriction base="xsd:string">
													<xsd:pattern value="\d{3}-\d{1,13}-\d{2}"/>
												</xsd:restriction>
											</xsd:simpleType>
										</xsd:element>
										<xsd:element name="PozivniBroj" type="xsd:string"/>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== nexylmao/MiBP3/xmlpodaci.xml
<?xml.version = "1.0"?>
<Uplatnice
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="randomlink xsd_sema.xsd"
	xmlns="randomlink"
	>
    <Uplatnica>
        <Uplatilac> Fakultet Tehnickih Nauka Trg Dositeja Obradovica 6 21000 Novi Sad</Uplatilac>
        <SvrhaPlacanja> Uplata po fakture br. 16 </SvrhaPlacanja>
        <Primalac> TELEKOM SRBIJA FIKSNA TELEFONIJA NOVI SAD Sutjeska 2 21000 Novi Sad</Primalac>
        <Iznos>
            <Valuta>RSD</Valuta>
            <Sifra>153</Sifra>
            <Iznos>8000.00</Iznos>
        </Iznos>
        <RacunUplatioca>
			<Model>97</Model>
			<BrojRacuna>840-1710660-30</BrojRacuna>
			<PozivniBroj>123-456</PozivniBroj>
        </RacunUplatioca>
        <RacunPrimaoca>
			<Model>97</Model>
			<BrojRacuna>380-3569852365147-42</BrojRacuna>
			<PozivniBroj>12345-67</PozivniBroj>
        </RacunPrimaoca>
    </Uplatnica>
	<Uplatnica>
        <Uplatilac> Nenad Vuletic\n Janka Cmelika 66\n 21000 Novi Sad</Uplatilac>
        <SvrhaPlacanja> Usluge </SvrhaPlacanja>
        <Primalac> SBB d.o.o \n Bulevar Zorana Djindjica 8a \n 11070 Beograd</Primalac>
        <Iznos>
            <Valuta>RSD</Valuta>
            <Sifra>189</Sifra>
            <Iznos>3300.00</Iznos>
        </Iznos>
        <RacunUplatioca>
			<Model>97</Model>
			<BrojRacuna>420-1337-21</BrojRacuna>
			<PozivniBroj>0-1</PozivniBroj>
        </RacunUplatioca>
        <RacunPrimaoca>
			<Model>97</Model>
			<BrojRacuna>170-1412-42</BrojRacuna>
			<PozivniBroj>111111111201708</PozivniBroj>
        </RacunPrimaoca>
    </Uplatnica>
</Uplatnice>
